import { StyleSheet } from "react-native";

const master = StyleSheet.create({
    container: {
        marginHorizontal: 10,
    },
    input: {
        borderColor: "black",
        borderWidth: 1,
        borderRadius: 4,
        fontSize: 30,
        padding: 10,
    },
    button: {
        backgroundColor: 'black',
        height: 60,
        width: 100,
    },
    relative: {position: 'relative'},
    absolute: {position: 'absolute'},
    overflow_hidden: {overflow: "hidden"},
    center: {
        justifyContent: 'center',
        alignItems: 'center',
    },
})

const margin = StyleSheet.create({
    _1: {margin: 1},
    _2: {margin: 2},
    _3: {margin: 3},
    _4: {margin: 4},
    _5: {margin: 5},
    _6: {margin: 6},
    _7: {margin: 7},
    _8: {margin: 8},
    _9: {margin: 9},
    _10: {margin: 10},
    _10: {margin: 10},
    _10: {margin: 10},
    _15: {margin: 15},
    _20: {margin: 20},
    _25: {margin: 25},
    _30: {margin: 30},

    t_1: {marginTop: 1},
    t_2: {marginTop: 2},
    t_3: {marginTop: 3},
    t_4: {marginTop: 4},
    t_5: {marginTop: 5},
    t_6: {marginTop: 6},
    t_7: {marginTop: 7},
    t_8: {marginTop: 8},
    t_9: {marginTop: 9},
    t_10: {marginTop: 10},
    t_15: {marginTop: 15},
    t_20: {marginTop: 20},
    t_25: {marginTop: 25},
    t_30: {marginTop: 30},

    b_1: {marginBottom: 1},
    b_2: {marginBottom: 2},
    b_3: {marginBottom: 3},
    b_4: {marginBottom: 4},
    b_5: {marginBottom: 5},
    b_6: {marginBottom: 6},
    b_7: {marginBottom: 7},
    b_8: {marginBottom: 8},
    b_9: {marginBottom: 9},
    b_10: {marginBottom: 10},
    b_15: {marginBottom: 15},
    b_20: {marginBottom: 20},
    b_25: {marginBottom: 25},
    b_30: {marginBottom: 30},

    r_1: {marginRight: 1},
    r_2: {marginRight: 2},
    r_3: {marginRight: 3},
    r_4: {marginRight: 4},
    r_5: {marginRight: 5},
    r_6: {marginRight: 6},
    r_7: {marginRight: 7},
    r_8: {marginRight: 8},
    r_9: {marginRight: 9},
    r_10: {marginRight: 10},
    r_15: {marginRight: 15},
    r_20: {marginRight: 20},
    r_25: {marginRight: 25},
    r_30: {marginRight: 30},

    l_1: {marginLeft: 1},
    l_2: {marginLeft: 2},
    l_3: {marginLeft: 3},
    l_4: {marginLeft: 4},
    l_5: {marginLeft: 5},
    l_6: {marginLeft: 6},
    l_7: {marginLeft: 7},
    l_8: {marginLeft: 8},
    l_9: {marginLeft: 9},
    l_10: {marginLeft: 10},
    l_15: {marginLeft: 15},
    l_20: {marginLeft: 20},
    l_25: {marginLeft: 25},
    l_30: {marginLeft: 30},

    x_1: {marginHorizontal: 1},
    x_2: {marginHorizontal: 2},
    x_3: {marginHorizontal: 3},
    x_4: {marginHorizontal: 4},
    x_5: {marginHorizontal: 5},
    x_6: {marginHorizontal: 6},
    x_7: {marginHorizontal: 7},
    x_8: {marginHorizontal: 8},
    x_9: {marginHorizontal: 9},
    x_10: {marginHorizontal: 10},
    x_15: {marginHorizontal: 15},
    x_20: {marginHorizontal: 20},
    x_25: {marginHorizontal: 25},
    x_30: {marginHorizontal: 30},

    y_1: {marginVertical: 1},
    y_2: {marginVertical: 2},
    y_3: {marginVertical: 3},
    y_4: {marginVertical: 4},
    y_5: {marginVertical: 5},
    y_6: {marginVertical: 6},
    y_7: {marginVertical: 7},
    y_8: {marginVertical: 8},
    y_9: {marginVertical: 9},
    y_10: {marginVertical: 10},
    y_15: {marginVertical: 15},
    y_20: {marginVertical: 20},
    y_25: {marginVertical: 25},
    y_30: {marginVertical: 30},
})

const padding = StyleSheet.create({
    _1: {padding: 1},
    _2: {padding: 2},
    _3: {padding: 3},
    _4: {padding: 4},
    _5: {padding: 5},
    _6: {padding: 6},
    _7: {padding: 7},
    _8: {padding: 8},
    _9: {padding: 9},
    _10: {padding: 10},
    _10: {padding: 10},
    _10: {padding: 10},
    _15: {padding: 15},
    _20: {padding: 20},
    _25: {padding: 25},
    _30: {padding: 30},

    t_1: {paddingTop: 1},
    t_2: {paddingTop: 2},
    t_3: {paddingTop: 3},
    t_4: {paddingTop: 4},
    t_5: {paddingTop: 5},
    t_6: {paddingTop: 6},
    t_7: {paddingTop: 7},
    t_8: {paddingTop: 8},
    t_9: {paddingTop: 9},
    t_10: {paddingTop: 10},
    t_15: {paddingTop: 15},
    t_20: {paddingTop: 20},
    t_25: {paddingTop: 25},
    t_30: {paddingTop: 30},

    b_1: {paddingBottom: 1},
    b_2: {paddingBottom: 2},
    b_3: {paddingBottom: 3},
    b_4: {paddingBottom: 4},
    b_5: {paddingBottom: 5},
    b_6: {paddingBottom: 6},
    b_7: {paddingBottom: 7},
    b_8: {paddingBottom: 8},
    b_9: {paddingBottom: 9},
    b_10: {paddingBottom: 10},
    b_15: {paddingBottom: 15},
    b_20: {paddingBottom: 20},
    b_25: {paddingBottom: 25},
    b_30: {paddingBottom: 30},

    r_1: {paddingRight: 1},
    r_2: {paddingRight: 2},
    r_3: {paddingRight: 3},
    r_4: {paddingRight: 4},
    r_5: {paddingRight: 5},
    r_6: {paddingRight: 6},
    r_7: {paddingRight: 7},
    r_8: {paddingRight: 8},
    r_9: {paddingRight: 9},
    r_10: {paddingRight: 10},
    r_15: {paddingRight: 15},
    r_20: {paddingRight: 20},
    r_25: {paddingRight: 25},
    r_30: {paddingRight: 30},

    l_1: {paddingLeft: 1},
    l_2: {paddingLeft: 2},
    l_3: {paddingLeft: 3},
    l_4: {paddingLeft: 4},
    l_5: {paddingLeft: 5},
    l_6: {paddingLeft: 6},
    l_7: {paddingLeft: 7},
    l_8: {paddingLeft: 8},
    l_9: {paddingLeft: 9},
    l_10: {paddingLeft: 10},
    l_15: {paddingLeft: 15},
    l_20: {paddingLeft: 20},
    l_25: {paddingLeft: 25},
    l_30: {paddingLeft: 30},

    x_1: {paddingHorizontal: 1},
    x_2: {paddingHorizontal: 2},
    x_3: {paddingHorizontal: 3},
    x_4: {paddingHorizontal: 4},
    x_5: {paddingHorizontal: 5},
    x_6: {paddingHorizontal: 6},
    x_7: {paddingHorizontal: 7},
    x_8: {paddingHorizontal: 8},
    x_9: {paddingHorizontal: 9},
    x_10: {paddingHorizontal: 10},
    x_15: {paddingHorizontal: 15},
    x_20: {paddingHorizontal: 20},
    x_25: {paddingHorizontal: 25},
    x_30: {paddingHorizontal: 30},

    y_1: {paddingVertical: 1},
    y_2: {paddingVertical: 2},
    y_3: {paddingVertical: 3},
    y_4: {paddingVertical: 4},
    y_5: {paddingVertical: 5},
    y_6: {paddingVertical: 6},
    y_7: {paddingVertical: 7},
    y_8: {paddingVertical: 8},
    y_9: {paddingVertical: 9},
    y_10: {paddingVertical: 10},
    y_15: {paddingVertical: 15},
    y_20: {paddingVertical: 20},
    y_25: {paddingVertical: 25},
    y_30: {paddingVertical: 30},
})


const color = StyleSheet.create({
    white: {color: 'white'},
})

export {master, margin, padding, color}